
#数据库配置信息
HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'flask-migrate_test'
USERNAME = 'ndpt'
PASSWORD = 'ndpt2018'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
 
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
